#!/usr/bin/env bash
set -euo pipefail

usage() {
  cat <<'USAGE'
Apply VS Code agent-orchestration scaffold to a target project.

Usage:
  scripts/apply-scaffold.sh <target-repo-path> [--force]

Examples:
  scripts/apply-scaffold.sh /Users/danedevalcourt/iPhoneApp/codex-pocket
  scripts/apply-scaffold.sh . --force

What it copies into target repo:
  .vscode-agent-orchestration/
    prompts/
    templates/
    docs/
    APPLIED_FROM.txt
USAGE
}

if [[ "${1:-}" == "-h" || "${1:-}" == "--help" || "$#" -lt 1 ]]; then
  usage
  exit 0
fi

TARGET_PATH="$1"
FORCE="${2:-}"

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"

if [[ ! -d "$TARGET_PATH" ]]; then
  echo "Target path does not exist: $TARGET_PATH" >&2
  exit 1
fi

TARGET_PATH="$(cd "$TARGET_PATH" && pwd)"
DEST_DIR="$TARGET_PATH/.vscode-agent-orchestration"

if [[ -e "$DEST_DIR" && "$FORCE" != "--force" ]]; then
  echo "Scaffold already exists at: $DEST_DIR" >&2
  echo "Re-run with --force to overwrite." >&2
  exit 1
fi

rm -rf "$DEST_DIR"
mkdir -p "$DEST_DIR"

cp -R "$ROOT_DIR/prompts" "$DEST_DIR/prompts"
cp -R "$ROOT_DIR/templates" "$DEST_DIR/templates"
cp -R "$ROOT_DIR/docs" "$DEST_DIR/docs"

cat > "$DEST_DIR/APPLIED_FROM.txt" <<EOF
source_repo: $ROOT_DIR
applied_at_utc: $(date -u +"%Y-%m-%dT%H:%M:%SZ")
notes: Generated by scripts/apply-scaffold.sh
EOF

cat > "$DEST_DIR/START_HERE.md" <<'EOF'
# Start Here

1) In VS Code Chat, install agents from this folder:
   - .vscode-agent-orchestration/prompts/orchestrator.md
   - .vscode-agent-orchestration/prompts/clarifier.md
   - .vscode-agent-orchestration/prompts/planner.md
  - .vscode-agent-orchestration/prompts/junior-dev.md
  - .vscode-agent-orchestration/prompts/frontend-dev.md
  - .vscode-agent-orchestration/prompts/backend-dev.md
  - .vscode-agent-orchestration/prompts/fullstack-dev.md
  - .vscode-agent-orchestration/prompts/sr-frontend-dev.md
  - .vscode-agent-orchestration/prompts/sr-backend-dev.md
  - .vscode-agent-orchestration/prompts/sr-fullstack-dev.md
  - .vscode-agent-orchestration/prompts/data-engineer.md
  - .vscode-agent-orchestration/prompts/designer.md
  - .vscode-agent-orchestration/prompts/prompt-writer.md
  - .vscode-agent-orchestration/prompts/devops.md
   - .vscode-agent-orchestration/prompts/executor.md
   - .vscode-agent-orchestration/prompts/reviewer.md

2) Select Orchestrator in the chat agent dropdown.

3) Paste:
   - .vscode-agent-orchestration/prompts/native-orchestrator-kickoff.md

4) Provide objective + constraints.
EOF

echo "Applied scaffold to: $DEST_DIR"
echo "Next: open $DEST_DIR/START_HERE.md"
